matrix:
  include:
    - language: rust
      rust: beta
      script:
        - cargo build --verbose
        - cargo run
        - cargo test --verbose
    - language: rust
      rust: nightly
      script:
        - cargo build --verbose
        - cargo run
        - cargo test --verbose
    - language: rust
      rust: stable
      script:
        - cargo build --verbose
        - cargo run
        - cargo test --verbose
    - language: node_js
      services:
        - docker
      node_js:
        - "8"
      script:
        - docker build -t slazaro/rust-wasm .
        - docker run slazaro/rust-wasm
  allow_failures:
    - rust: beta
    - rust: stable

sudo: required

dist: trusty

group: edge

