matrix:
  include:
    - language: rust
      rust: beta
      script:
        - cargo build --verbose
        - cargo run
        - cargo test --verbose
    - language: rust
      rust: nightly
      script:
        - cargo build --verbose
        - cargo run
        - cargo test --verbose
    - language: rust
      rust: stable
      script:
        - cargo build --verbose
        - cargo run
        - cargo test --verbose
    - language: node_js
      node_js:
        - "8"
      script:
        - sudo apt-get update
        - sudo apt-get install cargo
        - ./dev-tools/test-entrypoint.sh
        - npm test
  allow_failures:
    - rust: beta
    - rust: stable

sudo: true

dist: trusty

group: edge

