matrix:
  include:
    - language: rust
      rust: beta
      script:
        - cargo build --verbose
        - cargo run
        - cargo test --verbose
    - language: rust
      rust: nightly
      script:
        - cargo build --verbose
        - cargo run
        - cargo test --verbose
    - language: rust
      rust: stable
      script:
        - cargo build --verbose
        - cargo run
        - cargo test --verbose
    - language: node_js
      node_js:
        - "8"
      script:
        - cargo wa build --verbose
        - npm test
  allow_failures:
    - rust: beta
    - rust: stable

sudo: false

dist: trusty

group: edge

