matrix:
  include:
    - language: rust
      rust: beta
      script:
        - cargo build --verbose
        - cargo test --verbose
    - language: rust
      rust: nightly
      script:
        - cargo build --verbose
        - cargo test --verbose
    - language: rust
      rust: stable
      script:
        - cargo build --verbose
        - cargo test --verbose
    - language: node_js
      node_js:
        - "8"
      script:
        - npm test

sudo: false

dist: trusty

group: edge

